### ISSUE TITLE
Potential error with reading metadata using strings.Split(`: `)

### ISSUE THREAD

**Issue by northernorca** [hndada/rg-parser#1]
```
...
case "Metadata":
	kv := strings.Split(line, `:`)
	switch kv[0] {
	case "Title":
		o.Metadata.Title = kv[1]
	case "TitleUnicode":
		o.Metadata.TitleUnicode = kv[1]
...
```
The code is currently reading values by splitting "key: value" format with `strings.Split(': ')`, which can cause two potential errors when
1. the value is empty.
2. the value contains string ": ".

**Comment by hndada** [comment]
Reported via discord in advance, thanks for reporting! 
Fix soon.
